SELECT * FROM EMPLOYEES ORDER BY EMPLOYEE_ID
;

SELECT * FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 100
;

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME = INITCAP('john')
OR LAST_NAME = INITCAP('baida') --INITCAP 대소문자 구분하지 않음
;
